### ISSUE TITLE
Support for uploaded files

### ISSUE THREAD

**Issue by anachronic** [iyobo/amala#30]
I'd love to be able to inject uploaded files through [@koa/multer](https://github.com/koajs/multer). Just like routing-controllers does.

Would you accept a PR for this? I'd love to send you one.

**Comment by iyobo** [comment]
@anachronic Hey I appreciate that energy. It would certainly be a great addition!

**Comment by anachronic** [comment]
Sorry about inactivity, I've been a little busy.

After reading your comment, I'm thinking that adding a new decorator for files is just more boilerplate, and doesn't bring much to the table. Do we really want to add multer as a dependency just to have an extra decorator for uploaded files?

Isn't the way you describe above good enough for type inference?

**Comment by iyobo** [comment]
> Sorry about inactivity, I've been a little busy.
> 
> After reading your comment, I'm thinking that adding a new decorator for files is just more boilerplate, and doesn't bring much to the table. Do we really want to add multer as a dependency just to have an extra decorator for uploaded files?
> 
> Isn't the way you describe above good enough for type inference?

I would say No. It's not needed. The @flow decorator can be used to pipe file stuff in and can be defined on a whole api, controller or endpoint level.

**Comment by anachronic** [comment]
Alright, that's what I was thinking. I'm gonna close then.

Thanks!

**Comment by iyobo** [comment]
@anachronic I figured I'd do it anyway :)

Amala now has a new argument decorator `@File()` that you can use to access the dictionary of files uploaded to your endpoints. No need for added dependencies.

Enjoy!
