### ISSUE TITLE
Consult, constructor has no effect

### ISSUE THREAD

**Issue by beclass** [iyobo/amala#38]
![image](https://user-images.githubusercontent.com/12541388/162396632-5b86b42e-4296-4d2c-a9f7-f6009a773b5f.png)

How does the constructor take effect when the bootstrapControllers is initialized？

For example, like this ok
export class App{
  constructor(private name:string = "111"){
  }
  test(){
    console.log(this.name)
    console.log('test function')
  }
}
const app  = new App()
app.test()

**Comment by iyobo** [comment]
This actually works now.
