### ISSUE TITLE
Support OpenAPI spec file generation (JSON)

### ISSUE THREAD

**Issue by iyobo** [iyobo/amala#8]
This controller library gives endpoints all the self-documentation they need to generate OpenAPI spec files. 
Let's make that happen.

Ideally, the openAPI spec should be generated and cached during bootstrapControllers(...), the result of which can then be manually used by users as they deem fit.

e.g to serve from an endpoint or to be outputed into a JSON file. 

To keep this module simple and flexible, The specifics of how to output/use the spec file should be left to the users.

**Comment by iyobo** [comment]
See for example: https://petstore.swagger.io/v2/swagger.json

**Comment by brunozilio** [comment]
Hi, I really liked the project. Any predictions for this feature to be ready? I'm thinking of using it in an application;

**Good job!!!**

**Comment by iyobo** [comment]
OpenAPI spec is now sufficiently implemented for this to be closed.
